# Generated by Django 2.1.7 on 2020-02-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=42)),
                ('receiver', models.CharField(max_length=42)),
                ('message', models.TextField()),
                ('status_sender', models.CharField(choices=[('true', 'True'), ('false', 'False')], default='false', max_length=5)),
                ('status_receiver', models.CharField(choices=[('true', 'True'), ('false', 'False')], default='false', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_address', models.CharField(max_length=42)),
                ('nonce', models.CharField(default=12345, max_length=42)),
            ],
        ),
    ]
