# Generated by Django 2.1.7 on 2020-02-17 15:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chatsystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chats',
            name='time_sent',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
